# fly.toml app configuration file generated for tunnel-chat on 2025-09-03T17:36:59-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tunnel-chat'
primary_region = 'mia'

[build]

[http_service]
  internal_port = 8787
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
